swagger: '2.0'
paths:
  /GetMap:
    get:
      responses:
        '200':
          description: ''
      parameters:
        - name: service
          in: query
          required: true
          type: string
          description: Service name. Value is WMS
        - name: version
          in: query
          required: true
          type: string
          description: 'Service version. Value is one of 1.0.0, 1.1.0, 1.1.1, 1.3.0.'
        - name: request
          in: query
          required: true
          type: string
          description: Operation name. Value is GetMap.
        - name: layers
          in: query
          required: true
          type: string
          description: >-
            Layers to display on map. Value is a comma-separated list of layer
            names.
        - name: styles
          in: query
          required: true
          type: string
          description: >-
            Styles in which layers are to be rendered. Value is a
            comma-separated list of style names, or empty if default styling is
            required. Style names may be empty in the list, to use default layer
            styling.
        - name: srs
          in: query
          required: true
          type: string
          description: >-
            Spatial Reference System for map output. Value is in form EPSG:nnn.
            crs is the parameter key used in WMS 1.3.0.
        - name: bbox
          in: query
          required: true
          type: string
          description: >-
            Bounding box for map extent. Value is minx,miny,maxx,maxy in units
            of the SRS.
        - name: width
          in: query
          required: true
          type: string
          description: 'Width of map output, in pixels.'
        - name: height
          in: query
          required: true
          type: string
          description: "\tHeight of map output, in pixels."
        - name: format
          in: query
          required: true
          type: string
          description: "\tFormat for the map output. "
        - name: authkey
          in: query
          required: true
          type: string
          description: authorization key from AAC
        - name: transparent
          in: query
          required: false
          type: string
          description: >-
            Whether the map background should be transparent. Values are true or
            false. Default is false
        - name: bgcolor
          in: query
          required: false
          type: string
          description: >-
            Background color for the map image. Value is in the form RRGGBB.
            Default is FFFFFF (white).
        - name: exceptions
          in: query
          required: false
          type: string
          description: >-
            Format in which to report exceptions. Default value is
            application/vnd.ogc.se_xml.
        - name: time
          in: query
          required: false
          type: string
          description: 'Time value or range for map data. '
        - name: sld
          in: query
          required: false
          type: string
          description: >-
            A URL referencing a StyledLayerDescriptor XML file which controls or
            enhances map layers and styling
        - name: sld_body
          in: query
          required: false
          type: string
          description: >-
            A URL-encoded StyledLayerDescriptor XML document which controls or
            enhances map layers and styling
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      description: >-
        The GetMap operation requests that the server generate a map. The core
        parameters specify one or more layers and styles to appear on the map, a
        bounding box for the map extent, a target spatial reference system, and
        a width, height, and format for the output. The information needed to
        specify values for parameters such as layers, styles and srs can be
        obtained from the Capabilities document.


        The response is a map image, or other map output artifact, depending on
        the format requested. GeoServer provides a wide variety of output
        formats
      summary: Retrieves a map image for a specified area and content
  /GetCapabilities:
    get:
      responses:
        '200':
          description: ''
      summary: "\tRetrieves metadata about the service, including supported operations and parameters, and a list of the available layers"
      parameters:
        - name: service
          in: query
          required: true
          type: string
          description: Service name. Value is WMS.
        - name: version
          in: query
          required: true
          type: string
          description: 'Service version. Value is one of 1.0.0, 1.1.0, 1.1.1, 1.3.0.'
        - name: request
          in: query
          required: true
          type: string
          description: Operation name. Value is GetCapabilities.
        - name: namespace
          in: query
          required: false
          type: string
          description: "\tlimits response to layers in a given namespace"
        - name: format
          in: query
          required: false
          type: string
          description: "\trequest the capabilities document in a certain format"
        - name: authkey
          in: query
          required: true
          type: string
          description: authorization key from AAC
      description: >-
        The GetCapabilities operation requests metadata about the operations,
        services, and data (“capabilities”) that are offered by a WMS server.
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
  /GetFeatureInfo:
    get:
      parameters:
        - name: service
          in: query
          required: true
          type: string
          description: Service name. Value is WMS
        - name: version
          in: query
          required: true
          type: string
          description: 'Service version. Value is one of 1.0.0, 1.1.0, 1.1.1, 1.3.0.'
        - name: request
          in: query
          required: true
          type: string
          description: Operation name. Value is GetFeatureInfo.
        - name: layers
          in: query
          required: true
          type: string
          description: >-
            Layers to display on map. Value is a comma-separated list of layer
            names.
        - name: styles
          in: query
          required: true
          type: string
          description: >-
            Styles in which layers are to be rendered. Value is a
            comma-separated list of style names, or empty if default styling is
            required. Style names may be empty in the list, to use default layer
            styling.
        - name: srs
          in: query
          required: true
          type: string
          description: >-
            Spatial Reference System for map output. Value is in form EPSG:nnn.
            crs is the parameter key used in WMS 1.3.0.
        - name: bbox
          in: query
          required: true
          type: string
          description: >-
            Bounding box for map extent. Value is minx,miny,maxx,maxy in units
            of the SRS.
        - name: width
          in: query
          required: true
          type: string
          description: 'Width of map output, in pixels.'
        - name: height
          in: query
          required: true
          type: string
          description: "\tHeight of map output, in pixels."
        - name: authkey
          in: query
          required: true
          type: string
          description: authorization key from AAC
        - name: query_layers
          in: query
          required: true
          type: string
          description: Comma-separated list of one or more layers to query.
        - name: info_format
          in: query
          required: false
          type: string
          description: 'Format for the feature information response. '
        - name: feature_count
          in: query
          required: false
          type: string
          description: Maximum number of features to return. Default is 1.
        - name: x or i
          in: query
          required: true
          type: string
          description: >-
            X ordinate of query point on map, in pixels. 0 is left side. i is
            the parameter key used in WMS 1.3.0.
        - name: y or j
          in: query
          required: true
          type: string
          description: >-
            Y ordinate of query point on map, in pixels. 0 is the top. j is the
            parameter key used in WMS 1.3.0.
        - name: exceptions
          in: query
          required: false
          type: string
          description: >-
            Format in which to report exceptions. The default value is
            application/vnd.ogc.se_xml.
        - name: buffer
          in: query
          required: false
          type: string
          description: "\twidth of search radius around query point."
        - name: cql_filter
          in: query
          required: false
          type: string
          description: 'Filter for returned data, in ECQL format'
        - name: filter
          in: query
          required: false
          type: string
          description: 'Filter for returned data, in OGC Filter format'
        - name: propertyName
          in: query
          required: false
          type: string
          description: Feature properties to be returned
      responses:
        '200':
          description: ''
      summary: >-
        Retrieves the underlying data, including geometry and attribute values,
        for a pixel location on a map
      description: >-
        The GetFeatureInfo operation requests the spatial and attribute data for
        the features at a given location on a map. It is similar to the WFS
        GetFeature operation, but less flexible in both input and output. Since
        GeoServer provides a WFS service we recommend using it instead of
        GetFeatureInfo whenever possible.


        The one advantage of GetFeatureInfo is that the request uses an (x,y)
        pixel value from a returned WMS image. This is easier to use for a naive
        client that is not able to perform true geographic referencing.
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
  /DescribeLayer:
    get:
      responses:
        '200':
          description: ''
      parameters:
        - name: service
          in: query
          required: true
          type: string
          description: Service name. Value is WMS
        - name: version
          in: query
          required: true
          type: string
          description: 'Service version. Value is one of 1.0.0, 1.1.0, 1.1.1, 1.3.0.'
        - name: request
          in: query
          required: true
          type: string
          description: Operation name. Value is DescribeLayer.
        - name: layers
          in: query
          required: true
          type: string
          description: >-
            Layers to display on map. Value is a comma-separated list of layer
            names.
        - name: exceptions
          in: query
          required: false
          type: string
          description: >-
            Format in which to report exceptions. The default value is
            application/vnd.ogc.se_xml.
        - name: output_format
          in: query
          required: false
          type: string
          description: Response representation
        - name: authkey
          in: query
          required: true
          type: string
          description: authorization key from AAC
      summary: >-
        Indicates the WFS or WCS to retrieve additional information about the
        layer.
      description: >-
        The DescribeLayer operation is used primarily by clients that understand
        SLD-based WMS. In order to make an SLD one needs to know the structure
        of the data. WMS and WFS both have operations to do this, so the
        DescribeLayer operation just routes the client to the appropriate
        service.
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
  /GetLegendGraphic:
    get:
      responses:
        '200':
          description: ''
      parameters:
        - name: version
          in: query
          required: true
          type: string
          description: 'Service version. Value is one of 1.0.0, 1.1.0, 1.1.1, 1.3.0.'
        - name: request
          in: query
          required: true
          type: string
          description: Operation name. Value is GetLegendGraphic.
        - name: layer
          in: query
          required: true
          type: string
          description: Layer for which to produce legend graphic.
        - name: format
          in: query
          required: true
          type: string
          description: >-
            This gives the MIME type of the file format in which to return the
            legend graphic. Allowed values are the same as for the FORMAT=
            parameter of the WMS GetMap request.
        - name: authkey
          in: query
          required: true
          type: string
          description: authorization key from AAC
        - name: style
          in: query
          required: false
          type: string
          description: >-
            Style of layer for which to produce legend graphic. If not present,
            the default style is selected. The style may be any valid style
            available for a layer, including non-SLD internally-defined styles.
        - name: featuretype
          in: query
          required: false
          type: string
          description: >-
            Feature type for which to produce the legend graphic. This is not
            needed if the layer has only a single feature type.
        - name: rule
          in: query
          required: false
          type: string
          description: >-
            Rule of style to produce legend graphic for, if applicable. In the
            case that a style has multiple rules but no specific rule is
            selected, then the map server is obligated to produce a graphic that
            is representative of all of the rules of the style.
        - name: scale
          in: query
          required: false
          type: string
          description: >-
            In the case that a RULE is not specified for a style, this parameter
            may assist the server in selecting a more appropriate representative
            graphic by eliminating internal rules that are out-of-scope. This
            value is a standardized scale denominator, defined in Section 10.2.
            Specifying the scale will also make the symbolizers using Unit Of
            Measure resize according to the specified scale.
        - name: sld
          in: query
          required: false
          type: string
          description: >-
            This parameter specifies a reference to an external SLD document. It
            works in the same way as the SLD= parameter of the WMS GetMap
            operation.
        - name: sld_body
          in: query
          required: false
          type: string
          description: >-
            This parameter allows an SLD document to be included directly in an
            HTTP-GET request. It works in the same way as the SLD_BODY=
            parameter of the WMS GetMap operation.
        - name: width
          in: query
          required: false
          type: string
          description: >-
            This gives a hint for the width of the returned graphic in pixels.
            Vector-graphics can use this value as a hint for the level of detail
            to include.
        - name: height
          in: query
          required: false
          type: string
          description: This gives a hint for the height of the returned graphic in pixels.
        - name: exceptions
          in: query
          required: false
          type: string
          description: >-
            This gives the MIME type of the format in which to return
            exceptions. Allowed values are the same as for the EXCEPTIONS=
            parameter of the WMS GetMap request.
        - name: language
          in: query
          required: false
          type: string
          description: >-
            Allows setting labels language for style titles and rules titles;
            needs a correctly localized SLD to work properly; if labels are not
            available in the requested language, the default text will be used;
      summary: Retrieves a generated legend for a map
      description: >-
        The GetLegendGraphic operation provides a mechanism for generating
        legend graphics as images, beyond the LegendURL reference of WMS
        Capabilities. It generates a legend based on the style defined on the
        server, or alternatively based on a user-supplied SLD.
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
info:
  title: GeoServerWMS
  version: 1.0.0
